### ISSUE TITLE
WebServices broken 

### ISSUE THREAD

**Issue by muthuvenkat** [ebi-chebi/ChEBI#3286]
I ran the application last night and got the same error again. The error happened at 7:06:25 (this morning) while searching for Zn(2+). I don't think the search term (Zn) is the issue as there are other searches for Zn(2+) that was successful. Please could you take a look at your service ?  Meanwhile, is your REST service ready to use ?  This issue is a real blocker as we cannot complete our data release and we need to finish this before the end of this week.  Regards,  Joseph  Here is the error - still same as the one i sent yesterday  {code}  Caused by: com.sun.xml.ws.server.UnsupportedMediaException: Unsupported Content-Type: text/html Supported ones are: [text/xml] 	at com.sun.xml.ws.encoding.StreamSOAPCodec.decode(StreamSOAPCodec.java:295) 	at com.sun.xml.ws.encoding.StreamSOAPCodec.decode(StreamSOAPCodec.java:129) 	at com.sun.xml.ws.encoding.SOAPBindingCodec.decode(SOAPBindingCodec.java:360) 	at com.sun.xml.ws.transport.http.client.HttpTransportPipe.process(HttpTransportPipe.java:187) 	at com.sun.xml.ws.transport.http.client.HttpTransportPipe.processRequest(HttpTransportPipe.java:94) 	at com.sun.xml.ws.transport.DeferredTransportPipe.processRequest(DeferredTransportPipe.java:89) 	at com.sun.xml.ws.api.pipe.Fiber.__doRun(Fiber.java:598) 	at com.sun.xml.ws.api.pipe.Fiber._doRun(Fiber.java:557) 	at com.sun.xml.ws.api.pipe.Fiber.doRun(Fiber.java:542) 	at com.sun.xml.ws.api.pipe.Fiber.runSync(Fiber.java:439) 	at com.sun.xml.ws.client.Stub.process(Stub.java:222) 	at com.sun.xml.ws.client.sei.SEIStub.doProcess(SEIStub.java:135) 	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:109) 	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:89) 	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:118) 	at com.sun.proxy.$Proxy136.getLiteEntity(Unknown Source) 	at uk.ac.ebi.chebi.webapps.chebiWS.client.ChebiWebServiceClient.getLiteEntity(ChebiWebServiceClient.java:97)   {code}

**Comment by muthuvenkat** [comment]
We bounce everyday morning by that time, sorry for the inconvenience...
