### ISSUE TITLE
Malformed XML format in CHEBI:16551 

### ISSUE THREAD

**Issue by mmokrejs** [ebi-chebi/ChEBI#4182]
Hi,
  it seems ChEBI writes broken XML files with sharp brackets unescaped, breaking the XML syntax:

```
Debug: File CHEBI:16551.xml
Traceback (most recent call last):
  File "blah.py", line 252, in parse_chebi_xml
    etree=ET.parse(filename)
  File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 1229, in parse
    tree.parse(source, parser)
  File "/usr/lib/python3.9/xml/etree/ElementTree.py", line 580, in parse
    self._root = parser._parse_whole(source)
xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 23, column 25
```

  See the line 23 in the CHEBI:16551 entry.

With best regards,
Martin

**Comment by mmokrejs** [comment]
Likewise CHEBI:90163
