### ISSUE TITLE
Unable to search structures using the Java client or the web service

### ISSUE THREAD

**Issue by blanca-pueche** [ebi-chebi/ChEBI#4497]
When using the Java client there's a problem when calling the function getStructureSearch when calling it like this:
**LiteEntityList querySMILESResult = client.getStructureSearch(smiles, StructureType.SMILES, StructureSearchCategory.IDENTITY, 100, 0.90F);**
Getting this error with the following Identifier and SMILE: 
_Identifier{inchi=InChI=1S/C5H12O7P2/c1-5(2)3-4-11-14(9,10)12-13(6,7)8/h3H,4H2,1-2H3,(H,9,10)(H2,6,7,8), inchi_key=CBIDRCWHNCKSTO-UHFFFAOYSA-N, smiles=CC(C)=CCOP(O)(=O)OP(O)(O)=O}_

**Exception in thread "main" com.sun.xml.ws.fault.ServerSOAPFaultException: Client received SOAP Fault from server: java.lang.NullPointerException Please see the server log to find more detail regarding exact cause of the failure.
	at com.sun.xml.ws.fault.SOAP11Fault.getProtocolException(SOAP11Fault.java:163)
	at com.sun.xml.ws.fault.SOAPFaultBuilder.createException(SOAPFaultBuilder.java:98)
	at com.sun.xml.ws.client.sei.StubHandler.readResponse(StubHandler.java:223)
	at com.sun.xml.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:176)
	at com.sun.xml.ws.db.DatabindingImpl.deserializeResponse(DatabindingImpl.java:263)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:89)
	at com.sun.xml.ws.client.sei.SyncMethodHandler.invoke(SyncMethodHandler.java:62)
	at com.sun.xml.ws.client.sei.SEIStub.invoke(SEIStub.java:131)
	at jdk.proxy3/jdk.proxy3.$Proxy37.getStructureSearch(Unknown Source)
	at uk.ac.ebi.chebi.webapps.chebiWS.client.ChebiWebServiceClient.getStructureSearch(ChebiWebServiceClient.java:197)**

Trying the web service with the getLiteEntity function and inchi key: CBIDRCWHNCKSTO-UHFFFAOYSA-N, we get this:
**S:ServerERROR (General): we are having problems with this service... we are trying to rectify the situation.data 0: CBIDRCWHNCKSTO-UHFFFAOYSA-N, data 1: INCHI/INCHI KEY, ERROR (General): we are having problems with this service... we are trying to rectify the situation.**

and when trying the function getStructureSearch with the smile: CC(C)=CCOP(O)(=O)OP(O)(O)=O, we get this:
**S:Serverjava.lang.NullPointerException**

Thank you

**Comment by amalik01** [comment]
The ChEBI developer is currently taking a look at this issue.

**Comment by eloyfelix** [comment]
Dear Blanca, we had some issues in the database side of things when your issues ocurred. I understand you're not experiencing this issue anymore. Could you please confirm? Many thanks.

**Comment by blanca-pueche** [comment]
Thank you so much, it's working now.
